- name: Install Windows package
  win_chocolatey:
    name: "{{ package_name }}"
    params: "{{ parameters }}"
    state: latest
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"


- name: Start Windows service
  win_service:
    name: "{{ service_name }}"
    start_mode: auto
    state: started
  when: ansible_distribution == "Microsoft Windows Server 2012 R2 Standard"

- name: Create firewall rule for service
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    protocol: "{{ protocol_name }}"
    state: present
    enabled: yes
